### ISSUE TITLE
Converting into a Streamlit Component 🔨 

### ISSUE THREAD

**Issue by avrabyt** [avrabyt/Specklit#1]
Always goof to convert into a component for easy-usage.

### To-do - 
- [x] refactoring the functions
- [x] Creating modules separately
- [x] whether to include other features?

### Done -
- [x] Working with Specklit 
- [x] Deployable Streamlit App

**Comment by avrabyt** [comment]
@denphi Hey thanks for the heads up, I was just working on creating the component , few hours back in a separate branch! https://github.com/avrabyt/Specklit/tree/component-develop

Since it's developed I'll close it and use your stspeck module! 

Btw, great work on this pythonic speck, your work is very much appreciated within the streamlit community (here's my twitter thread on it - https://twitter.com/Avra_b/status/1527332154291593217)

And now you have this component done, wow 🚀 🎉 
Cheers
Avra

**Comment by avrabyt** [comment]
### stspeck is implemented in the latest release of [ipyspeck](https://pypi.org/project/ipyspeck/) 🚀  by @denphi 
`from ipyspeck import stspeck`

> @avrabyt, ipyspeck 0.6.1 includes a preliminary wrapper for streamlit, you should try it.
> 
> from ipyspeck import stspeck spec_xyz = stspeck.Speck( data=_xyz, atomScale=atom_Scale, bondScale=bond_Scale, outline=outline, atomShade=atom_Shade, bonds=bonds, relativeAtomScale=relativeAtomScale, bondThreshold=bondThreshold, width="800px", height="600px" )
